### ISSUE TITLE
Improve zeebe modeler prototype

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1076]
**Note**: Move this and the related tasks to new zeebe modeler repository. Atm it is located on [this repository](https://github.com/pinussilvestrus/zeebe-modeler-1).

In https://github.com/camunda/camunda-modeler/issues/1031 we were able to create a new Zeebe Modeler prototype as fork of the newly `camunda-modeler` architecture. To create a stable modeler, there are couple of things to do:

**Overall tasks**

- [ ] Update CHANGELOG.md
- [ ] Update README.md for instructions
- [ ] Move [issues](https://github.com/pinussilvestrus/zeebe-modeler/issues) to original [repo](https://github.com/zeebe-io/zeebe-modeler/issues)
- [x] Move [repository](https://github.com/pinussilvestrus/camunda-modeler) to zeebe organization,  handle [old repo](https://github.com/zeebe-io/zeebe-modeler)
- [ ] Check distro
- [ ] Setup CI https://github.com/pinussilvestrus/zeebe-modeler/issues/3
- [ ] Setup Codecov https://github.com/pinussilvestrus/zeebe-modeler/issues/13
- [ ] Move to master branch as default https://github.com/pinussilvestrus/zeebe-modeler/issues/11
- [ ] Release stable version

**Zeebe Tab**

- [x] Refactor to es6 https://github.com/pinussilvestrus/zeebe-modeler/issues/2
- [ ] Refactor zeebe custom modules in general https://github.com/pinussilvestrus/zeebe-modeler/issues/9
- [x] Add test coverage for custom zeebe modules https://github.com/pinussilvestrus/zeebe-modeler/issues/4
- [ ] Integrate zeebe deployment functionality https://github.com/pinussilvestrus/zeebe-modeler/issues/8

**Synchronization task**

- [x] Improve merge conflict handling [1] https://github.com/pinussilvestrus/zeebe-modeler/issues/7
- [x] Only create merge commit if there are real changes ([sync-fork#L247](https://github.com/pinussilvestrus/camunda-modeler/blob/next/tasks/sync-fork.js#L247) https://github.com/pinussilvestrus/zeebe-modeler/issues/7
- [ ] Improve error/ log handling https://github.com/pinussilvestrus/zeebe-modeler/issues/5
- [ ] Improve documentation https://github.com/pinussilvestrus/zeebe-modeler/issues/6
- [ ] Add test coverage https://github.com/pinussilvestrus/zeebe-modeler/issues/4
- [ ] **Discuss**: Implement commit message guideline to label commits inside `camunda-modeler` as unrelated for Zeebe Modeler?

**Nice to have** 
- [ ] sync-task: Make it more modular and configurable (e.g. handling merge commit message, upstream name, upstream branch, merge vs. rebase etc.), [`yargs`]( https://www.npmjs.com/package/yargs) ([sync-fork#L291](https://github.com/pinussilvestrus/camunda-modeler/blob/next/tasks/sync-fork.js#L291))
- [ ] sync-task: Push merge commit automatically? Automatically create pull request?
- [ ] sync-task: Get rid of simple-git dependency and built it via [`execa`](https://www.npmjs.com/package/execa/v/0.6.0)? ([sync-fork#L8](https://github.com/pinussilvestrus/camunda-modeler/blob/next/tasks/sync-fork.js#L8))
- [ ] sync-task: Move to own repo ?

[1] After excluding unrelated files, recheck existing merge conflicts. If no other exists, run git commit, otherwise offer auto merge tool for merge conflicts ([sync-fork#L234](https://github.com/pinussilvestrus/camunda-modeler/blob/next/tasks/sync-fork.js#L234))

**Comment by pinussilvestrus** [comment]
All changes will result in a Pull request on [zeebe-io/zeebe-modeler](https://github.com/zeebe-io/zeebe-modeler), work now happens mainly on this [fork](https://github.com/pinussilvestrus/zeebe-modeler-1/commits/migrate-to-camunda-modeler-next).

**Comment by pinussilvestrus** [comment]
Relates to https://github.com/zeebe-io/zeebe-modeler/issues/32

**Comment by pinussilvestrus** [comment]
Work is moved to https://github.com/zeebe-io/zeebe-modeler/issues/32. Close the issue on this repo.
