### ISSUE TITLE
Build Camunda Modeler @next (RC.1)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1116]
This is a follow up to https://github.com/camunda/camunda-modeler/issues/866 to track the progress towards a Camunda Modeler `@next` stable release.

__Items__

* [ ] Release `RC.1` https://github.com/camunda/camunda-modeler/issues/1174 @pinussilvestrus 
* [x] Properly save log on backend (https://github.com/camunda/camunda-modeler/issues/1156) @barmac 
* [x] Distinguish files by displaying full path on tab hover (https://github.com/camunda/camunda-modeler/issues/1187) @nikku 
* [x] Restore and fix shortcuts overlay (https://github.com/camunda/camunda-modeler/issues/1040, https://github.com/camunda/camunda-modeler/issues/1039) @pinussilvestrus 
* [x] CMD+SHIFT+Z does not redo command in the diagram (https://github.com/camunda/camunda-modeler/issues/1119) @barmac 
* [x] Tab links not updating properly (https://github.com/camunda/camunda-modeler/issues/1117) @philippfromme 
* [x] Fix nightly (https://github.com/camunda/camunda-modeler/issues/1128)
* [x] Cleanup old code
* [x] Cannot save converted activiti diagram (https://github.com/camunda/camunda-modeler/issues/1122) @barmac 
* [x] Restore file dropping (https://github.com/camunda/camunda-modeler/issues/1085) @barmac 
* [x] Uncaught error when dragging a file over drag tabs (https://github.com/camunda/camunda-modeler/issues/1120) @nikku 
* [x] Investigate `camunda-transaction-boundaries` blowing up Modeler (https://github.com/bpmn-io/camunda-transaction-boundaries/issues/6)
* [x] Properly wire all decision table keyboards shortcuts (https://github.com/camunda/camunda-modeler/issues/1061) @pinussilvestrus 
* [x] Moving elements and canvas not working inside decision diagram (https://github.com/camunda/camunda-modeler/issues/1146) @pinussilvestrus 
* [x] Save `isHorizontal=true` for Participant and Lane DI shapes (https://github.com/camunda/camunda-modeler/issues/1096) @barmac 
* [x] Add deployment source: "Camunda Modeler" (https://github.com/camunda/camunda-modeler/issues/1153) 
* [x] Restore plugin system (https://github.com/camunda/camunda-modeler/issues/1083) @philippfromme 
* [x] Restore custom copy/cut/paste behavior in decision table depending on selection range (https://github.com/camunda/camunda-modeler/issues/1060) @barmac 
* [x] Repair window menu (https://github.com/camunda/camunda-modeler/issues/1157) @barmac 
* [x] Restore file opening via CLI (https://github.com/camunda/camunda-modeler/issues/1161) @nikku 
* [x] Add ability to disable plug-ins via feature toggle (https://github.com/camunda/camunda-modeler/issues/1159) @nikku 
* [x] Restore close confirmation (https://github.com/camunda/camunda-modeler/issues/1162) @barmac 
* [x] Don't export negative DI coordinates (https://github.com/camunda/camunda-modeler/issues/982) @nikku 
* [x] External changes dialog opens twice (https://github.com/camunda/camunda-modeler/issues/1118) @pinussilvestrus 
* [x] Clarify supported environments (https://github.com/camunda/camunda-modeler/issues/1132)

**Comment by nikku** [comment]
Completed work on all items :balloon:
