### ISSUE TITLE
Clarify search paths in documentation

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1220]
Inside our `docs` we state the local search paths multiple times, e.g. for [plugins](https://github.com/camunda/camunda-modeler/tree/master/docs/plugins#plugging-into-the-camunda-modeler). It would be good to clarify them in _one_ place inside the documentation.

### Tasks

* [ ] Create new chapter `search paths` inside the [`docs`](https://github.com/camunda/camunda-modeler/tree/master/docs)
    * [ ] Explain and clarify local search paths (`APP_DIRECTORY`, `USER_DATA_DIRECTORY`, `APP_DATA` ... )
* [ ] Link `search paths` in other parts of the `docs`
    * [ ] [`element templates`](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates#configuring-templates)
    * [ ] [`flags`](https://github.com/camunda/camunda-modeler/tree/master/docs/flags)
    * [ ] [`plugins`](https://github.com/camunda/camunda-modeler/tree/master/docs/plugins#plugging-into-the-camunda-modeler)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1281.
