### ISSUE TITLE
Improve Editor fails to open journey

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1252]
> __Note:__ This is actually not a bug but a feature request. Read more in the __Expected Behavior__ section.

__Describe the Bug__

I cannot open the BPMN editor on Mac OS, starting with `v3.0.0-beta.0`.

__Steps to Reproduce__

* Download the latest beta release
* Unpack it (or install DMG)
* Open the editor
* See that the editor window is blank

Later in the process, we found out:

* Inspect the logs
* Realize an old version of token simulation is in the search path (cf. https://github.com/camunda/camunda-modeler/issues/1193)
* Realize that we do not properly handle tab errors (https://github.com/camunda/camunda-modeler/issues/1214)
* Disable plug-ins (complicated manual process right now) and see all is good

__Expected Behavior__

* [x] Still show UI (indicating a bug) https://github.com/camunda/camunda-modeler/issues/1214
* [x] Log bug / error with relevant context https://github.com/camunda/camunda-modeler/issues/1176
* [x] Give users a simple way to restart the app without plug-ins (if we detect that plug-ins may be the cause of the issue) https://github.com/camunda/camunda-modeler/issues/1252

__Environment__

Please complete the following information:

 - OS: MacOS, 10.14.3 (works fine on current Arch Linux)
 - Camunda Modeler Version: `v3.0.0-beta`

**Comment by barmac** [comment]
Closed via #1252
