### ISSUE TITLE
As a user I can copy and paste in two steps

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1421]
Investigate, whether a two step paste could circumvent https://github.com/camunda/camunda-modeler/issues/1416.

![capture XT8isL_optimized](https://user-images.githubusercontent.com/7633572/60809297-a3f7de00-a18a-11e9-8455-cdc2bf6622b8.gif)

__Tasks__

* [x] To be pasted elements are displayed in the same way as create previews are displayed and can be position / snapped freely on the diagram
* [x] Upon click elements are placed onto the designated target position

__Open Issues__

* [x] after paste, all elements should be selected https://github.com/bpmn-io/bpmn-js/issues/1152  @pinussilvestrus  
* [x] multi-element paste breaks grid alignment https://github.com/bpmn-io/bpmn-js/issues/1150 @philippfromme 
* [x] labels are lost during paste https://github.com/bpmn-io/bpmn-js/issues/921 @philippfromme 

---

Related to https://github.com/camunda/camunda-modeler/issues/238
Required by https://github.com/camunda/camunda-modeler/issues/1416

**Comment by philippfromme** [comment]
I've hacked together a small demo.

![08-07-_2019_14-13-28](https://user-images.githubusercontent.com/7633572/60809297-a3f7de00-a18a-11e9-8455-cdc2bf6622b8.gif)

Branches:
* [diagram-js#1421-two-step-pasting](https://github.com/bpmn-io/diagram-js/tree/1421-two-step-pasting)
* [bpmn-js#1421-two-step-pasting](https://github.com/bpmn-io/bpmn-js/tree/1421-two-step-pasting)
