### ISSUE TITLE
Improve Engine Deployments Experience

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1439]
This is a bulk issue for all issues related to the deployment tool.

* [x] Deploy dialog should be closable without input https://github.com/camunda/camunda-modeler/issues/1405
* [x] Pre-fill deployment endpoint with default input on first deploy https://github.com/camunda/camunda-modeler/issues/1441
* [x] Background check if the server is reachable https://github.com/camunda/camunda-modeler/issues/1444
* [x] Improve display of deployment parse errors https://github.com/camunda/camunda-modeler/issues/1426
* [x] Deploy and notify user outside of deploy dialog https://github.com/camunda/camunda-modeler/issues/839
* [x] Remember deployment details with diagram https://github.com/camunda/camunda-modeler/issues/1066
* [ ] Remember authentication details with endpoint configuration https://github.com/camunda/camunda-modeler/issues/1067

descoped for now
* [ ] Make re-deploy with same configuration the primary deploy button action https://github.com/camunda/camunda-modeler/issues/1440
* [ ] Store and use multiple endpoints https://github.com/camunda/camunda-modeler/issues/804

---

Cf. [UI sketches](https://docs.google.com/presentation/d/136nEfebFSh-JfBq4_PfFTzzF7BnKcTysvOgcu8ppx2A/edit#slide=id.g5bb2549018_0_46) for details on the complete picture.

**Comment by nikku** [comment]
@barmac @volkergersabeck I've prepared and linked the UI sketches to this issue.
