### ISSUE TITLE
Provide foundation for Cawemo extension

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1496]
This issue tracks the progress towards plug-in foundations for the [Cawemo plug-in](https://github.com/camunda/cawemo/issues/4520).

__Desired Solution__

From the Cawemo plug-in point of view we need the following capabilities:

* [x] A plug-in can hook into BPMN 2.0 XML being saved (before save, to inject meta-data)
* [x] A plug-in can hook into tab saved (after user saved)

This cannot be handled properly via a `bpmn.modeler` extension alone, as tab saved is a feature inherently _NOT_ exposed to the `bpmn.modeler`. Instead, we should allow users to create such capability via the newly created `editor` extension point.

Underlying technical capabilities required to support this:

* [x] Be able to contribute `bpmn.modeler` extensions via editor extension (https://github.com/camunda/camunda-modeler/issues/1499)
* [x] Be able to hook into `bpmn.modeler` post create via editor extension (https://github.com/camunda/camunda-modeler/issues/1500)
* [x] Be able to modfiy workspace configuration via editor extension (https://github.com/camunda/camunda-modeler/issues/1512)
* [x] Be able to hook into `tab.saved` via editor extension (https://github.com/camunda/camunda-modeler/issues/1498)
* [x] Test cover all things

__Solution Sketch__

Checkout the [`EditorEvents`](https://github.com/camunda/camunda-modeler/blob/1496-editor-events/client/src/plugins/editor-events/EditorEvents.js) extension on the [`1496-editor-events`](https://github.com/camunda/camunda-modeler/compare/1496-editor-events) branch that shows how to accomplish this.

**Comment by nikku** [comment]
Two incoming PRs:

* https://github.com/camunda/camunda-modeler/pull/1498, making plug-ins ready for internal release
* https://github.com/camunda/camunda-modeler/pull/1497, showcasing plug-in into the events

**Comment by nikku** [comment]
Closing this issue as `tab.saved`, the only thing Cawemo needed is implemented and merged.

**Comment by pinussilvestrus** [comment]
Everything seems to be done now, we also added sufficient test coverage for the extension points in my point of view. We should not test the showcases.
