### ISSUE TITLE
Users are able to learn about available upgrades

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1541]
__Is your feature request related to a problem? Please describe.__

We found that automatic updates (https://github.com/camunda/camunda-modeler/issues/20) may not be the best approach towards bringing updates to users quicker and identified update notifications as a good alternative that balances our requirements (cf. https://github.com/camunda/camunda-modeler/issues/1353 for rationale). 

__Describe the solution you'd like__

* [x] Users ask for their consent to participate in automatic update checks (https://github.com/camunda/camunda-modeler/issues/1543)
* [x] Given prior user consent the application checks on start against an update server, if an update is available (https://github.com/camunda/camunda-modeler/issues/1545)
* [x] Update checks are answered by an update server (https://github.com/camunda/camunda-modeler/issues/1546)
* [x] Enable update checks per default (https://github.com/camunda/camunda-modeler/issues/1641)

---

See also [specification document](https://docs.google.com/document/d/16Egw61QtZ8u2JHFrI1V7zIRWm7CtK5dE2OL-23BawY0)
