### ISSUE TITLE
Release Camunda Modeler v3.5.0

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1590]
Release Camunda Modeler `v3.5.0`

### What is inside

* [x] Numerous DMN (decision table + DRD) bug fixes
* [x] dmn-js updated to latest diagram-js foundation (https://github.com/bpmn-io/dmn-js/issues/412)
* [x] inverse connections for all toolkits (https://github.com/bpmn-io/diagram-js/issues/386)
* [x] Some BPMN bug fixes
* [x] ~Deployment: Make it a repetitive action~
* [x] Saving authentication details (https://github.com/camunda/camunda-modeler/issues/1067)
* [x] Sub-Processes are not collapsible anymore (https://github.com/camunda/camunda-modeler/issues/1486)
* [x] Supporting Camunda 7.12

### Prerequisites

* [x] mark `table-js` as compatible with `diagram-js@6` and release patch release @philippfromme 
* [x] mark `bpmn-js-properties-panel` as compatible with `bpmn-js@6` @pinussilvestrus 
* [x] release `bpmn-js-properties-panel` minor @pinussilvestrus 
* [x] release `diagram-js` major
* [x] release `bpmn-js` major
* [x] ~release `cmmn-js@0.20.0` minor~
* [x] ~mark `cmmn-js-properties-panel` as compatible with `cmmn-js@0.20.0`~
* [x] ~release `cmmn-js-properties-panel`~
* [x] integrate `table-js@latest` and `diagram-js@latest` into `dmn-js`
* [x] release `dmn-js@7.2.0` => pending releases of `dmn-js-decision-table`, `dmn-js-literal-expression`, and `dmn-js`
* [x] publish updated versions of utility libraries, marked as compatible with latest libs
* [x] integrate into Camunda Modeler: 
    * [x] `bpmn-js-properties-panel@latest`
    * [x] `dmn-js-properties-panel@latest`
    * [x] ~`cmmn-js-properties-panel@latest`~
    * [x] `diagram-js@latest`
    * [x] `dmn-js@latest`
    * [x] ~`cmmn-js@latest`~
    * [x] `bpmn-js@latest`
    * [ ] ...

### Checklist 

* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `sre`, and `Team-Support`)
* [x] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * `bpmn-js`, `dmn-js`, `cmmn-js`, `*-properties-panel`, `*-moddle`, ...
* [x] close all issues which are solved by dependency updates
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG
* [x] semantic release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
* [x] merge to master: `git checkout master && git merge develop`
* [x] wait for [Travis](https://travis-ci.org/camunda/camunda-modeler) to build the release
* [x] execute [integration test](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/camunda/camunda-modeler/releases)
    * [x] Works on Linux @philippfromme 
    * [x] Works on Mac @barmac @oguzeroglu 
    * [x] Works on Windows @philippfromme 
* [x] trigger QA for fuzzy testing
* [x] write blog post for [blog.camunda.org](https://github.com/camunda/blog.camunda.org), __do not publish until released version is available for download on [camunda.org](https://camunda.org/release/camunda-modeler/)__
* [x] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [x] trigger mirroring of release to https://camunda.org/release/camunda-modeler/ via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec)
* [x] update download version of Camunda Modeler at [camunda.com](https://github.com/camunda/camunda.com-new/blob/live/data/releases.json)
* [x] publish blog post on [blog.camunda.org](https://github.com/camunda/blog.camunda.org)
* [x] spread the word
    * [x] send [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/camunda-modeler/README.md#release-notice-email)
    * [x] tweet
* [x] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by nikku** [comment]
Found during integration testing: 

* BPMN Group not being correctly colored https://github.com/camunda/camunda-modeler/issues/1598

**Comment by nikku** [comment]
Additional issues found during testing:

* DRD append does not work anymore https://github.com/camunda/camunda-modeler/issues/1604
* Connections cannot be moved with DRD elements https://github.com/camunda/camunda-modeler/issues/1605
* Reconnection DRD connections serializes invalid `original="[object Object]"` property https://github.com/camunda/camunda-modeler/issues/1606

All of these seem to be regressions from our v3.4.1 release.

**Comment by barmac** [comment]
I can reproduce #1600 in Camunda Modeler 3.4.1, so it seems to not be a regression.
