### ISSUE TITLE
Use suitable text editor with syntax highlighting for editing XML

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#17]
#### TODO

* [x] tests dirty / initial state handling
* [x] test DMN tab
* [x] test app API changes
