### ISSUE TITLE
Fix Space Tool Issues

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1753]
# Issues related to the space tool

## UX

* [x] [Labels move twice when adding lane](https://github.com/bpmn-io/bpmn-js/issues/1302)
* [x] [Label is not sticky to flow nodes when space tool is applied](https://github.com/camunda/camunda-modeler/issues/1705)
* [x] [Space tool allows to leave boundary event floating around](https://github.com/camunda/camunda-modeler/issues/1750)
* [x] [Do not resize text annotation box when it's affected by create/remove space tool](https://github.com/camunda/camunda-modeler/issues/1371)
* [ ] [Missleading space tool preview](https://github.com/bpmn-io/bpmn-js/issues/1306)

## Interchangeability

* [x] [Move to Origin and Space Tool don't move embedded DI Label Coordinates](https://github.com/camunda/camunda-modeler/issues/1011)

**Comment by barmac** [comment]
Sketches: [excalidraw-202047162115.excalidraw.txt](https://github.com/camunda/camunda-modeler/files/4445282/excalidraw-202047162115.excalidraw.txt)

**Comment by philippfromme** [comment]
> [ ] [Missleading space tool preview](https://github.com/bpmn-io/bpmn-js/issues/1306)

This issue is not critical and can be tackled later.

**Comment by nikku** [comment]
Moving this to _fixed upstream as critical issues are fixed_.
