### ISSUE TITLE
Release Camunda Modeler v4.1.0

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1829]
## What's inside?

_Scheduled for 14th July_

*  [x] DMN Split View
* [x] `dmn-js@9` release (https://github.com/bpmn-io/dmn-js/issues/513),
  * [x] New Decision Table Layout and Editing
  * [x] New Literal Expression Layout
* [x] Ping to E.T. + report element templates used (https://github.com/camunda/camunda-modeler/issues/1805, https://github.com/camunda/camunda-modeler/issues/1850)
* [x] Closed tabs reopen after quit (https://github.com/camunda/camunda-modeler/issues/1795)
* [x] Send product name with update check (https://github.com/camunda/camunda-modeler-update-server/issues/36)

## Release Checklist

_To be done immediately after creating this issue._

* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `infra`, and `Team-Support`)

_To be done after code freeze and prior to the release day to prepare and build the release._

* [x] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * bpmn-js, dmn-js, cmmn-js, *-properties-panel, *-moddle, ...
    * [x] `bpmn-js`: Release and Integrate [`v7.3.0`](https://github.com/bpmn-io/bpmn-js/compare/v7.2.0...develop)
    * [x] `bpmn-js-properties-panel`: Release and Integrate [`v0.34.0`](https://github.com/bpmn-io/bpmn-js-properties-panel/compare/v0.33.1...master)
    * [x] `dmn-js`: Release and Integrate [`v9.0.0`](https://github.com/bpmn-io/dmn-js/issues/513)
    * [x] Bump [bpmn-js Extensions](https://github.com/camunda/camunda-modeler/issues/1837) versions
* [x] close all issues which are solved by dependency updates
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG (https://github.com/camunda/camunda-modeler/pull/1866)
* [x] semantic release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
* [x] merge to master: `git checkout master && git merge develop`
* [x] wait for [Travis](https://travis-ci.org/camunda/camunda-modeler) to build the release
* [x] execute [integration test](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/camunda/camunda-modeler/releases)
    * [x] Works on Linux @MaxTru 
    * [x] Works on Mac @pinussilvestrus 
    * [x] Works on Windows @philippfromme 
* [x] trigger QA for fuzzy testing
* [x] write blog post for [blog.camunda.org](https://github.com/camunda/blog.camunda.org), __do not publish until released version is available for download on [camunda.org](https://camunda.org/release/camunda-modeler/)__ @pinussilvestrus (https://github.com/camunda/camunda-modeler/issues/1861, https://github.com/camunda/blog.camunda.org/pull/171)

_To be done on release day to announce the release and making it publically available._

* [x] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [x] trigger mirroring of release to https://camunda.org/release/camunda-modeler/ via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec)
* [x] update download version of Camunda Modeler at [camunda.com](https://github.com/camunda/camunda.com-new/blob/live/data/releases.json)
* [x] publish blog post on [blog.camunda.org](https://github.com/camunda/blog.camunda.org)
* [x] spread the word
    * [x] send [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/camunda-modeler/README.md#release-notice-email)
    * [x] tweet
* [x] add new version to [updates-server](https://github.com/camunda/camunda-modeler-update-server) releases JSON file. Merge this file to master/live branches.
* [x] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by pinussilvestrus** [comment]
Release build triggered: https://travis-ci.org/github/camunda/camunda-modeler/builds/706565362

**Comment by MaxTru** [comment]
Works on Linux, 2 small OS-unrelated findings: 
https://github.com/camunda/camunda-modeler/issues/1871 https://github.com/camunda/camunda-modeler/issues/1874

**Comment by pinussilvestrus** [comment]
Things fixed for a potential Patch Release
* https://github.com/camunda/camunda-modeler/pull/1868
* #1869 
* #1871
