### ISSUE TITLE
Update Colors According to New Color Concept

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1844]
### Tasks

* [x] Decide whether colors in bpmn.io libraries (bpmn-js, ...) should be Camunda branded or overridden in Camunda Modeler
* [ ] Update bpmn.io modelers colors (diagram-js, bpmn-js, dmn-js, ...) https://github.com/bpmn-io/diagram-js/issues/476 https://github.com/bpmn-io/dmn-js/issues/539
* [x] Update properties panels colors (bpmn-js-properties-panel, dmn-js-properties-panel, ...) https://github.com/bpmn-io/bpmn-js-properties-panel/issues/338 https://github.com/bpmn-io/dmn-js-properties-panel/issues/17
* [ ] Update Camunda Modeler application colors

Concept: https://zpl.io/bzElEA4

Test artifacts: https://drive.google.com/drive/u/1/folders/1B6ihv08HKzC6SY1MDYbFVjBtpO1iGDGv

v1: Contains the designs of Andy **To be released as v4.2.0**
v2: Contains further improvements that we propose. **To be released later**
