### ISSUE TITLE
Update element-template documentation

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1945]
__Is your feature request related to a problem? Please describe.__

With https://github.com/camunda/camunda-modeler/milestone/54 a couple of enhancements are introduced to element-templates. This enhancements shall be reflected in the [docs](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates)

__Describe the solution you'd like__

Update documentation to include:
- [x] Updated screenshots (esp. element template search modal)
- [x] Updated description regarding Apply/Unlink/Remove logic https://github.com/camunda/camunda-modeler/issues/1889
- [x] Updated description regarding treating of non-present element-templates https://github.com/camunda/camunda-modeler/issues/1894
- [x] Reference to cloud:connect plugin https://github.com/camunda/cloud-connect-modeler-plugin/issues/17
- [x] Updated bindings configuration documentation / usage of "default" type for `camunda:inputParameter` and `camunda:outputParameter` about:blank
- [x] Remove or deprecate `entriesVisible` section (is not used anymore)
- [x] Remove or deprecate samples with `entriesVisible`
- [x] Add samples for the default rendering of `camunda:inputParameter` and `camunda:outputParameter`
- [x] Explain new parameter toggle
- [x] Explain that `default` rendering does not support `editable` or `constraints` config options
- [x] Remove disclaimer

__Describe alternatives you've considered__

n/a

__Additional context__

**Comment by MaxTru** [comment]
Potentially add: 
https://github.com/bpmn-io/bpmn-js-properties-panel/issues/376
https://github.com/bpmn-io/bpmn-js-properties-panel/issues/377

**Comment by pinussilvestrus** [comment]
We should also make sure to mention the new parameter toggle: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/372
