### ISSUE TITLE
Feature to "Close all tabs"

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#195]
I often have a lot of models open at once and to close them all i have to click close on each of them individually. It would be nice to be able to close all the open tabs at once.

### Tasks

Add to menu:

* [ ] add close all tabs
* [ ] add close other tabs

Investigate: 

* [ ] add to tab context menu?

**Comment by andreassiegelrfid** [comment]
In that context, it would also be nice to have "Close others" available.
