### ISSUE TITLE
Camunda Modeler supports BPMN Errors triggered via RPA Bridge

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2070]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

As part of the April CamBPM release, the RPA Bridge will support the triggering of BPMN errors. This shall be supported by the Camunda Modeler. 

An example looks like this:
```
    <bpmn:serviceTask id="ServiceTask_2" name="Generate quote"  camunda:type="external" camunda:topic="RPA">
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:inputParameter name="productName">${product}</camunda:inputParameter>
          <camunda:inputParameter name="count">${count}</camunda:inputParameter>
          <camunda:inputParameter name="price">${price}</camunda:inputParameter>
          <camunda:outputParameter name="pdfStorage">${pdfStorage}</camunda:outputParameter>
        </camunda:inputOutput>
        <camunda:properties>
          <camunda:property name="bot" value="PDFQuoteGenerator" />
        </camunda:properties>
        <camunda:errorEventDefinition id="CamundaErrorEventDefinition1" errorRef="Error_0x9vl7b" expression="${true}" />
        <camunda:errorEventDefinition id="CamundaErrorEventDefinition2" errorRef="Error_0x9vl7c" expression="${processVar}" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_04k3izd</bpmn:incoming>
      <bpmn:outgoing>Flow_1s764or</bpmn:outgoing>
    </bpmn:serviceTask>
```

In particular we need to (see child issues for more details):

**Priority 1**
- [x] Improve existing [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) UI for eventDefinitions. See [issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/421)
- [x] Support `camunda:errorEventDefinition` for external `ServiceTasks` in [Camunda Moddle](https://github.com/camunda/camunda-bpmn-moddle)
- [x] Implement new UI component supporting `camunda:errorEventDefinition` for external `ServiceTasks`. See [issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/422)
- [x] Support `camunda:errorEventDefinition` for external `ServiceTasks` with ElementTemplates
  - [x] Decide a concept, how `camunda:errorEventDefinition` can be configured using ElementTemplates (See https://miro.com/app/board/o9J_lZ7EwN0=/ and respective issues)
  - [x] Allow `scopes` to be an Array (rather than an Object as it is currently). Ensure backwards compatability (ie. still be able to scopes being an Object) [see issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/423)
  - [x] Support global entity `bpmn:Error` by adding new scoped binding type. [See issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/425)
  - [x] Implement new element template binding `camunda:errorEventDefinition` which allows to link an `bpmn:error` using the `errorRef` property [see issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/424)
  - [x] Adjust the elementTemplates jsonSchema to ensure compatibility (array scopes, error scopes, error event definition binding). See [issue for details.](https://github.com/camunda/element-templates-json-schema/issues/20)
  - [x] Support the transfer of all attributes on copy/pasting a service task defining a `camunda:ErrorEventDefinition`. ([See issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/442))
  - [x] Ensure the removal of `camunda:ErrorEventDefinition`-related attributes when changing the service task type from external to any other. ([See issue for details](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/441))
- [ ] Update element templates docs (https://github.com/camunda/camunda-modeler/issues/2161)
- [x] Release + integrate `element-templates-json-schema@0.3.0`

**Priority 2**
- [ ] Allow the reorder of `camunda:errorEventDefinitions`s of a given serviceTask by adding a "dragging" features for [the list of collapsbiles](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/422)
- [x] Adjust the elementTemplates jsonSchema
- [ ] Add support for all global entites (based on the concept established with `bpmn:Error`
- [ ] Add support for all eventDefinitions (based on the concept established with `camunda:errorEventDefinition`

__Why should we do it?__

The Camunda Modeler shall support the BPMN Error Trigger via RPA Bridge use case. See https://jira.camunda.com/browse/CAM-12040 for the CamBPM implementation.

__Context__
CamBPM implementation: https://jira.camunda.com/browse/CAM-12040
Concept-board https://miro.com/app/board/o9J_lZ7EwN0=/

**Comment by nikku** [comment]
Full feature is pending inclusion of latest camunda-bpmn-js (https://github.com/camunda/camunda-modeler/pull/2173) and should be in next nighly build once approved and merged. 

Could you @MaxTru give this a final review and close this issue if we're done? From my point of view https://github.com/camunda/camunda-modeler/pull/2173 checks all boxes. Remaining work (documentation is reflected in #2161 and worked on separately).

**Comment by MaxTru** [comment]
> Could you @MaxTru give this a final review and close this issue if we're done? 

Will do

**Comment by MaxTru** [comment]
Smoke test result:

> Ensure the removal of camunda:ErrorEventDefinition-related attributes when changing the service task type from external to any other. (See issue for details)

is not yet working. We need to publish the `0.42.0` version of the bpmn-js-properties-panel and bump in Camunda-Modeler

**Comment by nikku** [comment]
Integrated via https://github.com/camunda/camunda-modeler/pull/2173 as [mentioned above](https://github.com/camunda/camunda-modeler/issues/2070#issuecomment-806150622). Please check on the branch.

**Comment by MaxTru** [comment]
I tested on the develop branch.

IMO we still have a dependency to bpmn-js-properties-panel in Camunda Modeler.  (See Niklas comment https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L31). 

Either we bump bpmn-js-properties-panel here as well. Or we improve the setup (expose https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L31 via camunda-bpmn-js ?). I will touch this in the daily.

**Comment by nikku** [comment]
Merged https://github.com/camunda/camunda-modeler/pull/2173.

**Comment by MaxTru** [comment]
I did a final smoke test including:
* Configure errorEventDefinitions for external serviceTask
* Configure errorEventDefinitions for external serviceTask using elementTemplate
* CopyPaste Behavior
* Change impl type behavior

All looking good. Great job everyone!

Closing this ticket, since documentation is anyhow tracked seperately. Implementation wise we are done.

**Comment by MaxTru** [comment]
# Integration Test with Cawemo Team

**30.03.2021**

## Scope

![Screenshot_20210330_121535](https://user-images.githubusercontent.com/42800119/112973465-a6198180-9151-11eb-9aac-0e5e1aed0842.png)
(See [sep. issue] for integration test with platform team)

## Setup

* Camunda Modeler nightly from 29.03.2021
* Cawemo (xyz)
* Cloud Connect 3.0.0

## Test Cases

| No. | Case  | Result |
| ------------- | ------------- | ------------- |
| 1 | Template with single error: (1) can be applied (2) all values present (3) validation is the same  |   |
| 2 | Template with single error updated: (1) update dialog is offered (2) update works  |   |
| 3 | Template with multiple errors: (1) can be applied (2) all values present (3) validation is the same  |   |
| 4 | Template with multiple errors updated: (1) update dialog is offered (2) update works  |  |
