### ISSUE TITLE
Introduce schema-version for element templates

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2083]
__What should we do?__

Currently, [element templates](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates) don't define a schema or schema-version that they adhere to. 

This creates challenges:
* When we are changing element templates, these might not work in older Modeler version. Hence when loading these element templates, the Camunda Modeler will just throw a generic error message.

However, a solution is already available: the https://github.com/camunda/element-templates-json-schema repo defines a versioned schema, which can be used to...
* verify the validity of a given element template
* ensure that only element templates, which are supported in the current Camunda Modeler version, are loaded.

This issue proposes the following changes:

**Prio 1**
- [ ] ~~Add https://github.com/camunda/element-templates-json-schema as dependency~~
- [x] Element template schema json shall allow multiple element templates in an array as valid json (https://github.com/camunda/element-templates-json-schema/issues/15)
- [x] Release + integrate a version 0.3.0 of https://github.com/camunda/element-templates-json-schema, which includes the element templates changes introduced here: https://github.com/camunda/camunda-modeler/issues/2070
- [x] Update element templates to include a new field: `"$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.2.0/resources/schema.json"` (https://github.com/camunda/camunda-modeler/pull/2102)
- [x] Explicitly define in the codeBase, which element-template versions are supported (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/431)
- [x] When loading an element template, check the version compatability. If incompatabile, ignore the respective element template giving a meaningful notifaction (ala. "Vx.y.z of element templates is not supported, please update your Camunda Modeler to the latest version"). With the first release, support version `0.2.0` and yet to be released version `0.3.0` (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/431)
- [ ] Update the element template docs (https://github.com/camunda/camunda-modeler/issues/2161)
 
**Prio 2**
- [ ] ~~Validate the element template before applying it using https://github.com/bpmn-io/json-schema-validator and print the error to the user (if any)~~ (Will be tracked in https://github.com/camunda/camunda-modeler/issues/2159)

**Example**
```json
[
  {
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.2.0/resources/schema.json",    
    "name": "Template 1",
    "id": "sometemplate",
    "version": 1,
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      ...
    ]
  },
  {
    "name": "Template 2",
    ...
  }
]
```

__Why should we do it?__

This change will help us to manage changes in element templates in a more user-friendly way.

**Comment by MaxTru** [comment]
@pinussilvestrus  and @philippfromme could you please validate this enhancement proposal?

**Comment by pinussilvestrus** [comment]
> Update the element template docs

Related: https://github.com/camunda/camunda-modeler/issues/2008

**Comment by pinussilvestrus** [comment]
> If incompatabile, ignore the respective element template giving a meaningful notification

What do we do with templates which don't have a `$schema` defined?

**Comment by MaxTru** [comment]
> > If incompatabile, ignore the respective element template giving a meaningful notification
> 
> What do we do with templates which don't have a `$schema` defined?

Very good point, thanks! Added

**Comment by MaxTru** [comment]
Feedback from weekly
> `"$schema": "camunda/element-templates-json-schema@0.1.0/resources/schema.json"`

=> shall be a full URL. (unpkg, github, camunda)?
==> Next step let's see the options and then decide

**Comment by MaxTru** [comment]
Two follow-up questions:

**How to link the schema, so that also third party editors can access it?**

* **Option A**: relative link
  * "$schema": "camunda/element-templates-json-schema@0.1.0/resources/schema.json"
  * **Does not work for third party editors**
* **Option B**: link to unpkg
  * "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.2.0/resources/schema.json"
  * **Works for third party editors**  
  * (+) Free to use CDN
  * (+) Very fast (95% of unpkg's traffic is delivered via the CloudFare cache, which is on GoogleCloud across the globe)
  * (+) Used by various projects
  * (-) Strictly speaking: it does not provide uptime or support guarantees. Ref to the blog:
    * _unpkg is a free, best-effort service and cannot provide any uptime or support guarantees_
    *  _if you rely on it to serve files that are crucial to your business, you should probably pay for a host with well-supported infrastructure and uptime guarantees_
* **Option C**: publish to some Camunda resource and link to that resource
  * For example: "$schema": "https://downloads.camunda.cloud@camunda/element-templates-json-schema@0.2.0/resources/schema.json"
  * **Works for third party editors**  
  * (+) Reliable, in-house infrastructure
  * (-) More complex: release would require additional action to push to the backend
  * (-) element templates can be used outside the Camunda context, yet this would kind of bind it to Camunda
* **Option D**: publish to https://www.schemastore.org/javascript/ and link to that resource
  * For example: "$schema": "https://json.schemastore.org/element.templates-json-schema-0.3.0.json"
  * **Works for third party editors**  
  * (+) Easy / automatic discovery in various IDEs / JSON editors
  * (-) More complex: release would require additional action to push to the backend
  * (-) Strictly speaking: just as with unpkg we rely on them / it could potentially break
  * (-) I personally like how they do versioning. See [example commit (version as part of filename)](https://github.com/SchemaStore/schemastore/commit/4a509925fd458e31b092300d2f988e33650c0502#diff-1b8f038f5afb1158263a1fc83b9c0ca5a7438cceb90adad99d87168f70edc815R857)) 


**Can third-party editors deal with the schema structure. E.g, a single element template `.json` will contain an Array with multiple element templates, each could have a different $schema version**

WIP

**Comment by MaxTru** [comment]
**Decision Proposal**

**https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json**
Let's use unpkg.com. Since:
* Many other libraries use it
* No additional work for us
* The `@` "issue" is not an issue, since it would only impact the "out of the box" useability in VSCode, which is anyhow not given (see below)


-----------------------------------------------------

**Can third-party editors deal with the schema structure. E.g, a single element template .json will contain an Array with multiple element templates, each could have a different `$schema` version**
* In the element template json schema we will allow it to have multiple element templates in an array, or just an element template (see https://github.com/camunda/element-templates-json-schema/issues/15)
* This would not allow to direct out of the box support if you use Element Template Arrays by VSCode, but in this case the user may still simply add the schema to the project definition and would then get the editing support. For single element templates, this would work.

**Comment by MaxTru** [comment]
Related bug I found during development: https://github.com/camunda/camunda-modeler/issues/2110

**Comment by MaxTru** [comment]
Only thing missing: update of docs

**Comment by nikku** [comment]
Could you @MaxTru give this a final review and close this issue if we're done. Remaining work (documentation is reflected in https://github.com/camunda/camunda-modeler/issues/2161 and worked on separately).

**Comment by MaxTru** [comment]
Did final smoke test including:
* Unsupported schemaVersion shall be ignored
* Tested old scopes array design for camunda:Connector
* Tested new scopes object design for camunda:errorEventDefinitions

Great job everyone! Closing this issue (as @nikku stated, documentation is tracked seperately)
