### ISSUE TITLE
Integrate form editing into Camunda Modeler

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2135]
__What should we do?__

* [x] A new tab exists that holds the form editor (https://github.com/camunda/camunda-modeler/issues/2149)
* [x] `.form` files are recognized by the editor and opened on OS double click (https://github.com/camunda/camunda-modeler/issues/2149)
* [x] Forms can be loaded, edited and saved
* [x] `form-js` editor is integrated (https://github.com/camunda/camunda-modeler/issues/2150)
----

Depends on https://github.com/bpmn-io/form-js/issues/23

**Comment by barmac** [comment]
Related https://github.com/camunda/camunda-modeler/issues/2163

**Comment by MaxTru** [comment]
@philippfromme I assume this can be closed? Can you please check. Thanks

**Comment by philippfromme** [comment]
Yes! 👍🏻
