### ISSUE TITLE
bpmnlint Is Used to Lint BPMN Diagrams Based on Set Execution Platform

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2466]
[bpmnlint](https://github.com/bpmn-io/bpmnlint) is a sophisticated BPMN linter that is going to be used to lint BPMN diagrams.

### Tasks

* [ ] use bpmnlint to lint BPMN diagrams
* [ ] Hook up with existing Error display UI
* [ ] diagrams are linted using set execution platform and linting rules

---

Child of https://github.com/camunda/camunda-modeler/issues/2464

**Comment by nikku** [comment]
Incorporated via https://github.com/camunda/camunda-modeler/pull/2610.
