### ISSUE TITLE
Implement MVP for tracking user-flow analysis with Mixpanel

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2934]
__What should we do?__

Implement tracking for user-flow analysis with Mixpanel. This means tracking application-scoped events like `diagramOpened`, `diagramClosed`, `deployOpened`, ...

- [x] Define base properties to include in events' payload:
    - `distinctId`: editorID
    - `version`
    -  (if applicable) `executionPlatform`
    - (if applicable) `executionPlatformVersion`
    - `stage`: [int, dev, prod]
- [x] Define events to emit:

| Event         | Properties                     |  
|---------------|--------------------------------|
| diagram:opened |<ul><li>diagramType: [bpmn, dmn, form]</li></ul>|  
| diagram:closed |  <ul><li>diagramType: [bpmn, dmn, form]</li></ul>  | 
| overlay:deployment:opened  |  <ul><li>diagramType: [bpmn, dmn, form]</li></ul>  |   
| overlay:deployment:closed  |  <ul><li>diagramType: [bpmn, dmn, form]</li></ul> |   
| deployment:success  | <ul><li>diagramType: [bpmn, dmn, form]</li><li> targetType: [selfHosted, camundaCloud]</li></ul> |   
| deployment:error  | <ul><li>diagramType: [bpmn, dmn, form]</li><li> targetType: [selfHosted, camundaCloud]</li><li> error |   
| overlay:startInstance:opened  |   <ul><li>diagramType: [bpmn, dmn, form]</li></ul>   |   
| overlay:startInstance:closed  |  <ul><li>diagramType: [bpmn, dmn, form]</li></ul>  |   
| startInstance:success  |  <ul><li>diagramType: [bpmn, dmn, form]</li><li> targetType: [selfHosted, camundaCloud]</li></ul> |   
| startInstance:error  | <ul><li>diagramType: [bpmn, dmn, form]</li><li> targetType: [selfHosted, camundaCloud]</li><li> error |   
| overlay:versionInfo:opened | <ul><li>source: [menu or statusBar]</li></ul> |   
| link:opened |  <ul><li>link</li></ul>   |   
| button:clicked |  <ul><li>label</li></ul>   |   

- Integrate this in the Modeler using the prototype developed [here](https://github.com/camunda/camunda-modeler/tree/mixpanel-telemetry-prototype)
    - Set `stage` to `int` in "nightly" versions
    - [x] Add tab events (diagram:opened and tab:closed) - https://github.com/camunda/camunda-modeler/pull/2941
    - [x] Add deploy/startInstance events - https://github.com/camunda/camunda-modeler/pull/2986
    - [x] Add overlay events - https://github.com/camunda/camunda-modeler/pull/2941
    - [x] Add link/button events - https://github.com/camunda/camunda-modeler/pull/2981
- [x] Add project token as secret in Github repo

__Why should we do it?__

This allows us to do user flow-analysis and see all telemetry data in a central place. (e.g., combine Web Modeler and Desktop Modeler data). See https://github.com/bpmn-io/internal-docs/issues/504 for more.

Child of https://github.com/bpmn-io/internal-docs/issues/504

**Comment by christian-konrad** [comment]
I am unsure about the naming of "userTrackedEvent", as all of the events we track are user events. Any idea for a proper name (for example link:clicked and button:clicked)?

**Comment by smbea** [comment]
> I am unsure about the naming of "userTrackedEvent", as all of the events we track are user events. Any idea for a proper name (for example link:clicked and button:clicked)?

I agree. I would suggest `link:clicked` and `button:clicked` (or `item:clicked` and specify a type), userTrackedEvent to me is very ambiguous.

**Comment by christian-konrad** [comment]
I also suggest to name `startInstance:opened` to `startInstancePanel:opened` or `panel:startInstance:opened` or similar, same for deployment, to be less ambiquous (startInstance could also be the action itself)

**Comment by nikku** [comment]
If you ask me, let us "namespace" based on domains (i.e. `panel:startIstance:opened`, `panel:versionChooser:opened` and so forth).

**Comment by smbea** [comment]
There is a difference between interacting with UI components (opening an overlay) and performing actions (deploying to cloud). @nikku With that line of thought, do we keep the actions with the original naming of `deploy:...`?

**Comment by nikku** [comment]
I'd clearly namespace it to `overlay:xxx:open`, if that makes sense (or pick any prefix to distinguish `action` from `UI navigation`. This way we can track users as they navigate through our application.

**Comment by nikku** [comment]
Just a thought, of course. :)

**Comment by smbea** [comment]
I have started implementation with the definition above. @christian-konrad if you see anything that needs adapting/changing in the meantime let me know.

**Comment by smbea** [comment]
For the environment (stage: [int, dev, prod]):
Currently (in ET), the events from our nightly builds are mixed into the production events. **I propose** to set the `stage` to `dev` if we are dealing with a `...nightly...` version.

**Comment by nikku** [comment]
Sould we not set it to `int` (integration) on the nightly?

From what I understand we gotta set either (`int`, `dev`, `prod`), right?

**Comment by smbea** [comment]
Yes, `int` makes sense. My main point: separate these from the `prod` events

**Comment by MaxTru** [comment]
Discussed during weekly on 31.05.: @smbea to check with Annie whether it would not be better to send data to different mixpanel projects rather than using the `stage` property.

**Comment by smbea** [comment]
I have reached out to Annie and she said she would check on some things and get back to me regarding using different projects for different environments.
