### ISSUE TITLE
Update tracking for Forms Playground

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#3247]
__What should we do?__

We should update [our tracking](https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/) for the new Forms Playground integration. We currently only track opened/closed Forms files and their type. 

We want to track the following via Mixpanel:

- [ ] the panel toggle states (`formPlayground.layoutChanged`)
  - [ ] the engine profile to distinguish between C7 and C8 (and versions)
  - [ ] toggled via status bar vs. toggled via preview panel vs. toggled via keyboard

```json
{
  "event": "desktopModeler:formEditor:layoutChanged",
  "properties": {
    "executionPlatform": "Camunda Platform|Camunda Cloud",
    "executionPlatformVersion": "x.y",
    "layout": {
      "form-input": {
        "open": true
      },
      "form-output": {
        "open": true
      },
      "form-preview": {
        "open": true
      }
    },
    "triggeredBy": "keyboardShortcut|previewPanel|statusBar|windowMenu", 
  }
}
```    
    
- [ ] interactions with the input data, e.g. on focus out + changes made ("it was used")

```json
{
  "event": "desktopModeler:formEditor:inputDataChanged",
  "properties": {
    "executionPlatform": "Camunda Platform|Camunda Cloud",
    "executionPlatformVersion": "x.y"
  }
}
```    

- [ ] interactions with the preview, e.g. on focus out + changes made ("it was used")

```json
{
  "event": "desktopModeler:formEditor:previewChanged",
  "properties": {
    "executionPlatform": "Camunda Platform|Camunda Cloud",
    "executionPlatformVersion": "x.y"
  }
}
```    

- [ ] update [telemetry docs](https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/) => https://github.com/camunda/camunda-platform-docs/pull/1463

In the future, we'd like to have a generic tracking framework (cf. similar to https://github.com/bpmn-io/bpmn-js-tracking/issues/1). For now, it's okay to keep it in the Desktop Modeler. 

__Why should we do it?__

Track the adoption of the new Form Playground in the Desktop Modeler.

Child of #3126
Related to https://github.com/camunda/product-hub/issues/129 (`Success Metrics`)

**Comment by pinussilvestrus** [comment]
*Sync with @christian-konrad*

We want to

- track: the panel toggle states (`formPlayground.layoutChanged`)
- track: toggled via status bar vs. toggled via preview panel vs. toggled via keyboard
  - idea: add context to `layoutChanged` event
- where to track: Mixpanel
- track: interactions with the input data, e.g. on blur + changes made ("it was used")
- track: interactions with the preview, e.g. focus + blur

I added the requirements to the issue description.

On a side note: We consider tracking the same once integrated the playground into the bpmn-io demo (cf. https://github.com/bpmn-io/bpmn-io-demo/issues/107).
