### ISSUE TITLE
Update release template checklist 

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#3271]
### What should we do?

Update release template links and tasks:

**Updates:**
- [x] Update outdated links in the [release template checklist](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/RELEASE.md)
- [x] Remove _"(if the Modeler UI appearance changed)"_. Since we added the version to the status bar, the screenshots will always change
- [x] Adjust screenshot guide to use the workflow: https://github.com/camunda/camunda-docs-modeler-screenshots/actions/workflows/createScreenshots.yml

When blog post handbook docs is updated:
- [ ] Update blog post protocol 

**Potential improvement:**
- [x] Generate release versions automatically (`lerna publish preminor --preid rc`)

### Why should we do it?

To keep the release checklist up to date and help release commanders releasing successfully.

**Comment by marstamm** [comment]
We should also consider to:

- adjust screenshot guide to use the workflow: https://github.com/camunda/camunda-docs-modeler-screenshots/actions/workflows/createScreenshots.yml
- generate release versions automatically (`lerna publish preminor --preid rc`)

**Comment by nikku** [comment]
We have https://github.com/bpmn-io/internal-docs/issues/721 scheduled as a follow-up. Maybe we can improve our contribution / interaction with the marketing / PMM team.
