### ISSUE TITLE
Define element templates for typed events (Message, Error, Compensation)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#343]
Make it possible to define element templates for typed events such as Message, Error, Signal (Throw|Catch) events.

Cf. [forum thread](https://forum.camunda.org/t/element-templates-not-powerful-enough-for-signal-event-with-execution-listener/842) with inspiration for template extensions and friends.

### Tasks

* [ ] create extension in JSON
* [ ] apply extension to definitions
* [ ] update definitions on change

**Comment by falko** [comment]
My current consulting customer needs this, especially for Signal Events.

**Comment by nikku** [comment]
This should be supported by https://github.com/camunda/camunda-modeler/issues/308.

**Comment by Ichigo85** [comment]
Hi all. With this feature will it be possible to define also <messageEventDefinition> on intermediateThrowEvent? I tried to define a scoped template for it (with a delegate expression and field injections)and found that it does not work now and came up to this issue.

**Comment by nikku** [comment]
@Ichigo85 Correct.

**Comment by Ichigo85** [comment]
Hi @nikku . Since I need this feature for my company and I would like to contribute and learn how to develop on bpmn-js/camunda modeler project, I already started a few months ago to create some camunda plugin and add a few modification to my camunda modeler fork. Is there something that I can do for this contribution? Can you redirect me to some documentation or code to start? I saw that element templates are in bpmn-js-properties-panel module, right?

**Comment by nikku** [comment]
As you've mentioned, you'd need to contribute to the [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) to bake in the functionality.

Which feature set would you like to support?

**Comment by nikku** [comment]
Prior work has been done to support what we call _scoped_ templates for `camunda:Connector`: https://github.com/camunda/camunda-modeler/issues/308. If possible we should re-use the created infrastructure.

**Comment by MaxTru** [comment]
Feedback from customer in NA via CSM: this is a high-priority requirement, they would love to have it. cc @nikku

**Comment by billbarni** [comment]
6 years. Any news on this? Enterprise client needs this...

**Comment by philippfromme** [comment]
This has been partially implemented: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/906
