### ISSUE TITLE
Remove ET tracking completely

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#3486]
### What should we do?

Stop using ET completely and rely only on Mixpanel. We should:

- [x] Remove [`usage-statistics`](https://github.com/camunda/camunda-modeler/tree/develop/client/src/plugins/usage-statistics) plugin (ET tracking module)
- [x] Migrate ["PING" event](https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/#definition-of-events) to Mixpanel
- [x] Update [docs](https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry) accordingly. Leave only information being sent with Mixpanel (_eg._ `diagramMetrics` will not be sent anymore): https://github.com/camunda/camunda-platform-docs/pull/1850

**Event name:** `desktopModeler:ping` 
**Event structure:**
```json
 "plugins": ["PLUGIN_NAME"],
  "flags": {
    "FLAG_NAME": "FLAG_VALUE"
```

### Why should we do it?

We are not using the data on ET anymore so let's remove it so we don't have to maintain it.

**Comment by smbea** [comment]
@CatalinaMoisuc Not yet. I submitted on thursday and it said 2-3 days so it may be looked at today. But I will check in on it.

My progress on this is on [this branch](https://github.com/camunda/camunda-modeler/tree/3486-remove-et) so I can pick it up whenever we get the ok

**Comment by KingYannai** [comment]
@smbea reviewed this event with me and confirmed that @christian-konrad is using this metric. In that case, looks good to me and thanks for the heads up. When it's in Mixpanel, please let me know and I'll update the lexicon.

**Comment by smbea** [comment]
Testing with the nightly artifact, I discovered a bug that will be fixed via https://github.com/camunda/camunda-modeler/pull/3521

**Comment by smbea** [comment]
@KingYannai These changes have been merged and will be live from April 11th (next release date)
