### ISSUE TITLE
Support `bpmn:TimeDate` for Timer Boundary and Intermediate Catch Events

### ISSUE THREAD

**Issue by Wolgo** [camunda/camunda-modeler#3516]
```[tasklist]
### Tasks
* [x] https://github.com/camunda/camunda-bpmn-js-behaviors/issues/35
* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/913
* [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/95
```

-----

Related to https://github.com/camunda/zeebe/pull/12118

**Comment by nikku** [comment]
@Wolgo Please share a full model that shows this option in use. This helps us to better assess the impact of the bug you're reporting.

**Comment by Wolgo** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0pdudxn" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.9.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.1.0">
  <bpmn:process id="Process_1fzqfid" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_0d3umdu</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_0d3umdu" sourceRef="StartEvent_1" targetRef="Activity_1wd4599" />
    <bpmn:endEvent id="Event_08mod0e">
      <bpmn:incoming>Flow_07cwdb1</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_07cwdb1" sourceRef="Activity_1wd4599" targetRef="Event_08mod0e" />
    <bpmn:endEvent id="Event_1892y09">
      <bpmn:incoming>Flow_1scptpx</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1scptpx" sourceRef="Event_0fkuc9m" targetRef="Event_1892y09" />
    <bpmn:receiveTask id="Activity_1wd4599" messageRef="Message_0e67kd6">
      <bpmn:incoming>Flow_0d3umdu</bpmn:incoming>
      <bpmn:outgoing>Flow_07cwdb1</bpmn:outgoing>
    </bpmn:receiveTask>
    <bpmn:boundaryEvent id="Event_0fkuc9m" cancelActivity="false" attachedToRef="Activity_1wd4599">
      <bpmn:outgoing>Flow_1scptpx</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_1o0qtzv">
        <bpmn:timeDate xsi:type="bpmn:tFormalExpression">="2019-10-01T12:00:00Z"</bpmn:timeDate>
      </bpmn:timerEventDefinition>
    </bpmn:boundaryEvent>
  </bpmn:process>
  <bpmn:message id="Message_0e67kd6" name="Message_0e67kd6">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=&#34;3&#34;" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1fzqfid">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="209" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_08mod0e_di" bpmnElement="Event_08mod0e">
        <dc:Bounds x="422" y="209" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1892y09_di" bpmnElement="Event_1892y09">
        <dc:Bounds x="292" y="82" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1uelo91_di" bpmnElement="Activity_1wd4599">
        <dc:Bounds x="270" y="187" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1jcg2w9_di" bpmnElement="Event_0fkuc9m">
        <dc:Bounds x="292" y="169" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0d3umdu_di" bpmnElement="Flow_0d3umdu">
        <di:waypoint x="215" y="227" />
        <di:waypoint x="270" y="227" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_07cwdb1_di" bpmnElement="Flow_07cwdb1">
        <di:waypoint x="370" y="227" />
        <di:waypoint x="422" y="227" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1scptpx_di" bpmnElement="Flow_1scptpx">
        <di:waypoint x="310" y="169" />
        <di:waypoint x="310" y="118" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
`

**Comment by Wolgo** [comment]
A minimal example. 
I think it's purely a value missing in the list of options, as I can deploy this instance just fine. 
So I hope to fix it tonight when I am done working. Sadly can't put in the time to fix this at work.

**Comment by nikku** [comment]
@Wolgo, potenially, yes. 

I verified that this is indeed a bug / valid use of BPMN.

**Comment by nikku** [comment]
If you'd look into a fix, happy to take a contribution.

**Comment by nikku** [comment]
Reached out to the Zeebe core team just to double-check.

**Comment by nikku** [comment]
@Wolgo I've received confirmation that the documentation is right and that `timeDate` is not officially supported in Zeebe. Cf. https://github.com/camunda/zeebe/issues/5141.

**Comment by nikku** [comment]
Turned into a feature request.

**Comment by aleksander-dytko** [comment]
@nikku with https://github.com/camunda/zeebe/issues/5141 done, can we maybe support this also from the modeler side?

**Comment by aleksander-dytko** [comment]
Thanks @nikku 🚀
