### ISSUE TITLE
Support receive task message templates

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3573]
Just like Message Events, Receive Tasks should also be configurable via element templates. Most of the infrastructure is already there, but test coverage is missing. You cannot create a buggy template accidentally as it's not allowed via JSON schema.
```[tasklist]
### Tasks
- [x] I can create a Receive Task template
- [x] I can configure bpmn:Message#property binding for Receive Task
- [x] I can configure bpmn:Message#zeebe:subscription#property binding for Receive Task
- [x] I can read documentation on receive task templating
```

**Comment by barmac** [comment]
Documentation is coming via https://github.com/camunda/camunda-docs/pull/2950
