### ISSUE TITLE
Form Deployment and Linking via Latest Binding

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3656]
_Tracked via https://github.com/camunda/product-hub/issues/419._

### Breakdown

```[tasklist]
### Tasks
- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/949
- [ ] https://github.com/camunda/camunda-bpmn-js-behaviors/pull/49
- [ ] https://github.com/camunda/camunda-modeler/pull/3952
- [ ] https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/144
```

### C7 Reference

For reference, this is what setting a form reference looks like for Camunda 7:

![image](https://github.com/camunda/camunda-modeler/assets/7633572/d05e88b7-d7fd-4462-b591-6fcbd1c6e4a8)

And this is what deploying forms looks like for Camunda 7:

![image](https://github.com/camunda/camunda-modeler/assets/7633572/5611a849-0da8-4c80-8b5d-0ba4c6501242)

**Comment by philippfromme** [comment]
Since we're using [`zeebe-node`](https://github.com/camunda-community-hub/zeebe-client-node-js) support for the new API needs to be added to that library.

**Comment by nikku** [comment]
We support the new deploy resource API since https://github.com/camunda/camunda-modeler/commit/331f80306b0f02208527d205acd0b5f29c51eb9b. Does that unblock https://github.com/camunda/camunda-modeler/issues/3656#issuecomment-1677267662?

**Comment by philippfromme** [comment]
> We support the new deploy resource API since [331f803](https://github.com/camunda/camunda-modeler/commit/331f80306b0f02208527d205acd0b5f29c51eb9b). Does that unblock [#3656 (comment)](https://github.com/camunda/camunda-modeler/issues/3656#issuecomment-1677267662)?

Yes, but whether we will build deployment for the desktop modeler is to be determined.

**Comment by smbea** [comment]
Since this seems like an epic, shouldn't it stay in backlog? Since it doesn't have an attached PR, it gets confusing in the review column

**Comment by nikku** [comment]
Moved back to ready, thanks for the hint @smbea.

**Comment by nikku** [comment]
Confirmed with @CatalinaMoisuc and @christian-konrad that we want to support deployment of forms (standalone), too.

**Comment by philippfromme** [comment]
With all tasks being done we can close this issue.
