### ISSUE TITLE
Support multi-tenancy (C8) when deploying or running a process

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3716]
_Tracking issue for [multi-tenancy support](https://github.com/orgs/camunda/projects/80/views/1) in Camunda 8._

### Problem you would like to solve

As a user I want to use [Zeebe's upcoming multi-tenancy feature](https://github.com/camunda/zeebe/issues/12653) from the desktop modeler.

### Breakdown

* [x] Update zeebe-node to make `tenantId` available :arrow_right: https://github.com/camunda/camunda-modeler/issues/3772)
* [x] I can specify a `tenantId` in _deploy dialog_ to use a specific tenant ([design specification](https://github.com/camunda/modeler-design/issues/185#issuecomment-1665633521)) :arrow_right:  https://github.com/camunda/camunda-modeler/pull/3826
* [x] Incorporate zeebe node with actual `tenantId` support (https://github.com/camunda-community-hub/zeebe-client-node-js/issues/330)
* [x] Verify error handling (https://github.com/camunda/web-modeler/issues/5765#issuecomment-1713481696)
* [x] Integrate zeebe-node with multi-tenancy support
* [ ] [Update documentation](https://camunda.slack.com/archives/C0555930H7F/p1696505937202799)

### Alternatives considered

None.

### Additional context

Depends on https://github.com/camunda/zeebe/issues/12653.

----

Requires support for multi-tenancy to be baked into [zeebe-node](https://www.npmjs.com/package/zeebe-node).

Depends on https://github.com/camunda-community-hub/zeebe-client-node-js/issues/330.

**Comment by nikku** [comment]
Related, cf. [web modeler issue](https://github.com/camunda/web-modeler/issues/5058) and [implementation kick-off notes](https://docs.google.com/document/d/1nnKXzmtc91Fv6mV0KVrCU2PlhiAumQ93A9qbJqAQI_c/edit).

**Comment by nikku** [comment]
Reached out to [zeebe-node maintainer](https://camunda.slack.com/archives/C05M5TCMG9X) to clarify when the API we require is going to ship.

**Comment by nikku** [comment]
Thanks to @jwulf we got stubbed `tenantId` support incorporated https://github.com/camunda/camunda-modeler/issues/3772. I'll next tackle the UI parts on our end.

**Comment by nikku** [comment]
Work in progress PR integrating the UI :arrow_right: https://github.com/camunda/camunda-modeler/pull/3826.

**Comment by nikku** [comment]
Work is in progress on a [`zeebe-node` version](https://camunda.slack.com/archives/C05M5TCMG9X/p1697454889893159) that supports multi-tenancy.

**Comment by nikku** [comment]
Work regarding the UI integration is completed.

**Comment by nikku** [comment]
Error handling done using the standard means (error dialog).

**Comment by nikku** [comment]
Integration done.
