### ISSUE TITLE
When modeling a Call Activity, I can configure if all parent variables must be propagated or not

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#3793]
### Problem you would like to solve

Currently, Zeebe always propagates all variables from the parent process instance to the child process instance when executing a call activity. This leads to many redundant data across the called process instances, resulting in a larger runtime state in Zeebe. Additionally, all the variables need to be imported by the webapps (like Operate, and so on).

With https://github.com/camunda/zeebe/issues/13959, Zeebe introduces a new property called `propagateAllParentVariables` so that users can decide if they want to propagate all variables or only specific one:

1. (Default) `propagateAllParentVariables = true`, all variables from the parent process instance are propagated to the child process instance
2. `propagateAllParentVariables = false`, only the variables defined via _input mappings_ are propagated to the child process instance.

The property can be configured per Call Activity.

Basically, with this feature request, a user should be able to configure the property `propagateAllParentVariables`

### Proposed solution

Similar to the existing _Output Propagation_, a group _Input Propagation_ exists which contains a toggle to turn enable/disable the propagation of all variables. By default, when modeling a new Call Activity, the toggle is enabled (i.e. on).

### Tasks
- [x] https://github.com/camunda/zeebe-bpmn-moddle/issues/50
- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/953
- [x] Validate version compatibility for `propagateAllParentVariables`, cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat
  - [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/123
  - [x] https://github.com/camunda/linting/issues/81

### Alternatives considered

No.

### Additional context

The resulting BPMN XML is supposed to be the following
```
<bpmn:callActivity id="CallActivity_1">
  <bpmn:extensionElements>
    <zeebe:calledElement propagateAllParentVariables="true|false" />
  </bpmn:extensionElements>
</bpmn:callActivity>
```

---

related to https://github.com/camunda/zeebe/issues/13959 (Zeebe)
related to https://github.com/camunda/product-hub/issues/141 (Product Hub Epic)

**Comment by nikku** [comment]
@romansmirnov If we implement this then we want to add a validation rule, too? Cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat. This way users know when this property becomes available.

**Comment by romansmirnov** [comment]
@nikku, yes, makes sense. I would love to open a PR therefore, but I would need a short intro to the linting plugin. Would you be available, therefore? 😄

**Comment by nikku** [comment]
Looks like we're on track to ship this with the next release.

**Comment by nikku** [comment]
Shipped upstream via [@camunda/linting@3.6.0](https://github.com/camunda/linting/blob/main/CHANGELOG.md#360), [bpmn-js-properties-panel@5.1.0](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/main/CHANGELOG.md#510).

**Comment by philippfromme** [comment]
Integrated into Camunda Modeler:

![electron_0BOkg0Ib0p](https://github.com/camunda/camunda-modeler/assets/7633572/7e5f7dd9-9344-4819-8a15-c9a4d002ae3e)

**Comment by barmac** [comment]
This is cool but we forgot to document it at https://docs.camunda.io/docs/next/components/modeler/bpmn/call-activities/
