### ISSUE TITLE
Support BPMN in color

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#390]
Make it possible to set colors on individual tasks, events, connections etc.

See https://github.com/bpmn-io/bpmn-js/issues/494 and https://github.com/bpmn-io/bpmn-js-properties-panel/issues/199 for more details.

* [x] Extend bpmn-moddle to support colors (similar to https://github.com/bpmn-io/dmn-moddle/blob/master/resources/dmn/bpmn-io/biodi.json) https://github.com/bpmn-io/bpmn-moddle/issues/43
* [x] add bpmn-js support for colored strokes and fills, decide on what parts of an element should be colored https://github.com/bpmn-io/bpmn-js/issues/629
* [x] add possibility to assign colors to a group of elements (fill color and slightly darker stroke color) https://github.com/bpmn-io/bpmn-js/issues/630
* [x] color is assigned and persisted in BPMN XML
* [ ] add color picker with basic colors to modeler toolbar https://github.com/camunda/camunda-modeler/issues/445

---

See also [SUPPORT-2553](https://app.camunda.com/jira/browse/SUPPORT-2553).
