### ISSUE TITLE
`get or else` Camunda FEEL function is marked as syntax error

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3983]
### Describe the bug

When I choose `get or else` function from the suggestions, it's marked as syntax error.

https://github.com/camunda/camunda-modeler/assets/28307541/dc541efa-f69a-40b3-b21a-9cea66dfcd8d

### Steps to reproduce

1. Start writing `get or` and notice the suggestion
2. Hit enter
3. now this happens

### Expected behavior

The expression `get or else(variable, defaultValue)` should be parsed as:

```
Expression [0, 35]
  FunctionInvocation [0, 35]
    VariableName [0, 11]
    PositionalParameters [12, 34]
      VariableName [12, 20]
      VariableName [22, 34]
```

This must be tuned in a bunch of places, cf. breakdown at the end of the issue description.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

The built-in extension function should be provided in the context because it uses keywords.

[SUPPORT-19273](https://jira.camunda.com/browse/SUPPORT-19273)
[SUPPORT-23453](https://jira.camunda.com/browse/SUPPORT-23453)
[SUPPORT-23592](https://jira.camunda.com/browse/SUPPORT-23592)
[SUPPORT-26284](https://jira.camunda.com/browse/SUPPORT-26284)
[SUPPORT-28024](https://jira.camunda.com/browse/SUPPORT-28024)
[SUPPORT-28017](https://jira.camunda.com/browse/SUPPORT-28017)

----

The fix for this issue is to enable `camunda` built-ins in the linting parts of our editing stack, where they are available.

### Work items

A log of prior work on this topic:

* [x] https://github.com/bpmn-io/feel-lint/pull/23
* [x] https://github.com/bpmn-io/feel-editor/pull/68
* [x] Provide `camunda` built-ins context for FEEL linting
  * [x] extract camunda-builtins from editor (https://github.com/camunda/feel-builtins/pull/1) 
  * [x] migrate feel-editor to extracted camunda-builtins (https://github.com/bpmn-io/feel-editor/pull/71)
  * [x] enable feel-lint to take builtins directly (https://github.com/bpmn-io/feel-lint/pull/36)
  * [x] utilize extracted camunda-builtins in bpmnlint-plugin-camunda-compat(https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/206
* [x] https://github.com/bpmn-io/properties-panel/pull/396
* [x] Adopt / inject `camunda` built-ins in the relevant places (BPMN, DMN)
* [ ] Improve performance of feel linting (https://github.com/nikku/lezer-feel/issues/59, https://github.com/camunda/camunda-modeler/issues/5203) 
* [ ] [[S]](https://en.wikipedia.org/wiki/MoSCoW_method#should) In other places (FORM), indicate that `camunda` built-ins are not provided (https://github.com/camunda/camunda-modeler/issues/4603)

---

Related to https://github.com/camunda/camunda-modeler/issues/3338
Requires https://github.com/camunda/camunda-modeler/issues/5219

**Comment by marstamm** [comment]
We could add a quick-fix and add it to the expression context, but that would not solve the underlying issue. We are currently supporting two FEEL engines with different capabilities, but use the same editor tooling for both.

Cf. @nikku comment on Slack: https://camunda.slack.com/archives/GP70M0J6M/p1699970314078889?thread_ts=1699954926.982759&cid=GP70M0J6M

We should try to solve it on the language level. In the long term, we need a decision on how to handle extensions, especially when we want to add a FEEL playground in the modeler experience at one point.

**Comment by JeromeiMSA** [comment]
Hi,

The same problem occurs with Camunda Modeler 5.18.0 : 

![image](https://github.com/camunda/camunda-modeler/assets/108665511/4d0ac395-10bd-4fe3-81e9-3bb63768f921)

But, we can deploy the BPMN diagram on platform 8.3. And the process works correctly.

**Comment by barmac** [comment]
This has been independently reported by multiple users.

**Comment by nikku** [comment]
Moving to `backlog`.

**Comment by nikku** [comment]
Let's investigate if this is an easy pick.

**Comment by nikku** [comment]
Did not make it into the `M76` milestone.

**Comment by nikku** [comment]
I looked into this yesterday and found that there is sensible improvements we could make in the [`feel-editor`](https://github.com/bpmn-io/feel-editor):

* Any declared built-in shall also be available for syntax completion
* We can make better use of the batteries included in code mirror for retrieving available variables and built-ins.

**Comment by nikku** [comment]
@barmac Assigning myself as I'll look into this post release (I have the context still).

**Comment by nikku** [comment]
Updating the `feel-editor` unfortunately does not solve the issue:

![image](https://github.com/camunda/camunda-modeler/assets/58601/4e61c1f8-12dc-41e4-adbf-fc1b457092f7)

What I missed is that we'd also need to update our FEEL validation to recognize the `get or else` built-in.

**Comment by nloding** [comment]
Adding another user report so priority can be adjusted as needed: https://forum.camunda.io/t/unparsable-feel-expression-is-it-a-bug-in-modeler/53862/

**Comment by nikku** [comment]
Thanks. A fix is already work in progress.

**Comment by valeriaportolesicamunda** [comment]
Another customer has reported this: [SUPPORT-23453](https://jira.camunda.com/browse/SUPPORT-23453)

**Comment by rtkohl** [comment]
Another customer has reported this: [SUPPORT-23592](https://jira.camunda.com/browse/SUPPORT-23592).
is there any workaround for this or an estimated date on when this will be fixed? My customer is using 8.5

**Comment by Eilenn** [comment]
Any updates?

**Comment by nikku** [comment]
Removing my assignment, as I'll not be able to work on this any time soon. Let's check @barmac how we can get it incorporated.

**Comment by philippfromme** [comment]
There's another support case asking for a fix: https://jira.camunda.com/browse/SUPPORT-26284

**Comment by Buckwich** [comment]
I'm not able to properly reproduce this in the dmn editor. Am I doing something wrong? I still get the error for backticks and for `get or else` in the bpmn-js fields but not in the table or literal expression: 

<img width="516" alt="Image" src="https://github.com/user-attachments/assets/d51b598b-7d95-46a1-ab1f-f272b7aea796" />

**Comment by barmac** [comment]
Same, but I don't know why it's the way it is. I checked the `variables` provided to the editor, and `get or else` was not among them. 
Backticks are still reported as syntax error at demo.bpmn.io/dmn:

![Image](https://github.com/user-attachments/assets/fdc28540-17dd-470c-8a0a-11e8e1970a2e)

**Comment by valeriaportolesicamunda** [comment]
@barmac was this issue fixed for Web Modeler as well?

**Comment by Buckwich** [comment]
due to performance [issues](https://github.com/nikku/lezer-feel/issues/59) in the feel language tooling we needed to [revert](https://github.com/camunda/camunda-modeler/pull/5210) this change for now.

**Comment by nikku** [comment]
> @barmac was this issue fixed for Web Modeler as well?

@valeriaportolesicamunda This was temporarily fixed for both tools, but will (unfortunately) be [reverted](https://github.com/camunda/camunda-modeler/issues/3983#issuecomment-3190940408), as it caused regressions for our users. 

We intend to fix it in the future. But the fix has been removed from current web modeler and upcoming Camunda Modeler v5.38.1 version. Please consider that in your communication.

**Comment by Buckwich** [comment]
@valeriaportolesicamunda the original implementation would have applied to web and deskop modeler. but we got reports (from web modeler users) of degraded performance so we reverted the change

**Comment by nikku** [comment]
Back to `ready` to discuss with the team how to approach this next.

**Comment by vobu** [comment]
+1 on this for Start Events.
Both Web Modeler and Desktop Modeler.

<img width="475" height="231" alt="Image" src="https://github.com/user-attachments/assets/70d620e0-88d0-41b2-933e-c4be51a49fe6" />

**Comment by Buckwich** [comment]
I just realized we don't need to provide the whole context/builtin to linting. Only the problematic functions (those that have feel keywords like `else` in their name) eg `get or else` can be injected to get the parser to work. So only injecting 1 additional context instead of [all builtins](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/215/files) shouldn't affect performance

**Comment by misslisserw** [comment]
Thank you for working on this. I spent a long time of trial/error trying to fix something that modeler says was invalid, but wasn't.  I'm glad I tried to deploy anyway, and it allowed it thru and could verify working at runtime. Now that I'm aware of this function's existence, we will have this on so many nodes in our models. Looking forward to clearing all the false errors that confuse our less technical viewers.

**Comment by nikku** [comment]
This will be fixed via https://github.com/camunda/camunda-modeler/pull/5625. 🎉

**Comment by misslisserw** [comment]
I see this is closed and shows fixed in camunda-modeler v5.45.0, but what about web modeler in Camunda 8.8 self-managed?

**Comment by nikku** [comment]
@misslisserw Which version of web modeler do you use? It is fixed with Web Modeler 8.9 and [SaaS](https://modeler.camunda.io)

**Comment by misslisserw** [comment]
In my post I mentioned Camunda 8.8. We used camunda-platform-13.8.0 for the upgrade from 8.7. I guess we will have to wait until we upgrade to 8.9.
