### ISSUE TITLE
Track FEEL popup editor usage

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4004]
### What should we do?

Be able to track popup editor open and close to capture its usage. We want to capture popup editor usage for all editors, and understand in which editor (Form, BPMN) it is used.

#### Tasks

* [x] Track it via [bpmn-js-tracking](https://github.com/bpmn-io/bpmn-js-tracking).
* [x] Integrate in Desktop Modeler (https://github.com/camunda/camunda-modeler/pull/4083)

#### Follow-up

* [ ] Integrate in Web Modeler

To consider: Is there additional tracking we need to access [popup editor usage](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1000)? 

### Why should we do it?

What we cannot track, we cannot validate easily.

----

Brought up in [this conversation](https://camunda.slack.com/archives/C032H77434N/p1701337984986399).

**Comment by nikku** [comment]
@marstamm Let's ensure we get this integrated end-to-end.

**Comment by nikku** [comment]
@marstamm Do you also prepare a web modeler PR? To be integrated [here](https://github.com/camunda/web-modeler/blob/aeeb274b55fb242a31c53dc5f31c512bb94a9f1e/webapp/src/App/Pages/Diagram/BpmnViewer.js#L134) I believe.

**Comment by marstamm** [comment]
Web modeler already bumped it via https://github.com/camunda/web-modeler/pull/7764 and uses the "all" export which already includes popup editor tracking. No more action required from our side
