### ISSUE TITLE
Automatically assign current iteration milestone when closing an issue

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4311]
### What should we do?

I'd like to automatically assign a current iteration milestone when closing (merged) a Camunda Modeler issue or PR. This ensures we are organized (out of the box), and no additional changes housekeeping is needed. The following activities could easily be automated:

* [ ] Closing of release milestone (once release issue is closed)
* [ ] Support notification (https://github.com/bpmn-io/internal-docs/pull/990)
* [ ] Opening of new release milestone
* [ ] Adding issues (as they are closed or moved to `needs review`) to current release milestone 

How this could work:

* We source the current milestone via the "latest milestones" view, or via the milestone attached to the [release issue](https://tasks.bpmn.io/board/?c=%21Done%2CFixed+Upstream%2C%21Inbox&s=repo%3A%22camunda%2Fcamunda-modeler%22+label%3A%22release%22+is%3Aopen+)
* We ensure that the release issue always has a milestone attached (`M{LAST_NUMBER + 1}`).
  * Milestone is created following our usual pattern, linking back to the planed modeler release number (https://github.com/camunda/camunda-modeler/milestones?state=closed).
  * Milestone is linked to [release issue](https://tasks.bpmn.io/board/?c=%21Done%2CFixed+Upstream%2C%21Inbox&s=repo%3A%22camunda%2Fcamunda-modeler%22+label%3A%22release%22+is%3Aopen+)

### Why should we do it?

This ensures we do less manual house keeping behind the scenes, and still ensure that our tracking is kept in tact.

---

Related to https://github.com/bpmn-io/internal-docs/issues/910 (and would massively improve the existing integration).

**Comment by nikku** [comment]
Moving to `ready` to discuss with the team.

**Comment by barmac** [comment]
I'm wondering why we don't name the milestone after the release version. "M80" sounds less useful than "v5.24.0".

**Comment by nikku** [comment]
We could consider this. There is a number of things that we can improve.

**Comment by nikku** [comment]
Would probably be `5.24` as a name then.

**Comment by nikku** [comment]
Created https://github.com/camunda/camunda-modeler/issues/4406 as a follow-up.

**Comment by nikku** [comment]
Created https://github.com/camunda/camunda-modeler/issues/4405 as a follow-up.
