### ISSUE TITLE
Investigate if manual notarization is still needed

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4578]
### What should we do?

We currently [manually notarize](https://github.com/camunda/camunda-modeler/blob/develop/tasks/after-sign/notarize.js) builds of the app for MacOS. To me it appears like this is supported by [electron builder](https://www.electron.build/app-builder-lib.interface.macconfiguration#notarize). 

#### Tasks

* [ ] Perform notarization through [electron-builder](https://www.electron.build/app-builder-lib.interface.macconfiguration#notarize)
  * [ ] Adjust secrets to enable it
  * [ ] Migrate secrets to vault in the process (https://github.com/bpmn-io/internal-docs/issues/802)

### Why should we do it?

This will allow us to drop the direct notarization dependency and use what is provided and tested in the builder.

**Comment by nikku** [comment]
Tagging as spring cleaning, maybe we also tackle this as part of https://github.com/camunda/camunda-modeler/issues/4588.
