### ISSUE TITLE
Make DMN modeling great again

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#705]
There is still work to be done beyond #697 to make DMN modeling in the Camunda Modeler great again:

__Major Items__

* [x] DRD modeler generates DI, if non-existing https://github.com/bpmn-io/dmn-js/issues/264
* [x] Be able to return to DRD from decision table https://github.com/camunda/camunda-modeler/issues/700
* [x] Consistent (ID / name) editing and validation in decision table view https://github.com/bpmn-io/dmn-js/issues/245
* [x] Connections in DRD are updated on Decision ID change (in table view) https://github.com/bpmn-io/dmn-js/issues/263
* [x] All libraries got released with a __major version bump__
* [x] Project  Logo added to decision table https://github.com/bpmn-io/dmn-js/issues/268

__Minor Items__

_(Without these, people can still model DMN, just won't feel too convenient)_
 
* [x] Restore `editorActions` / menu integration #707
