### ISSUE TITLE
Produce signed modeler builds for Windows and MacOS

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#787]
__Tasks__

* [x] ship existing archives with signed executables
* [x] offline installer, per user installer (64 bit only)
    * [x] DMG for Mac
    * [x] Nsis for Windows
* [x] Drop auto wiring of file association in app
    * [x] Provide support script to wire associations with archive
    * [x] automatically wire file association via installer
    * [ ] document manual wiring [here](https://docs.camunda.org/manual/7.9/installation/camunda-modeler/) (https://github.com/camunda/camunda-modeler/issues/852)
* [x] Release artifacts to GitHub releases
* [ ] Release nightly artifacts (https://github.com/camunda/camunda-modeler/issues/848)
* [ ] Mirror to Camunda releases (https://github.com/camunda/camunda-modeler/issues/851)
* [x] Integration Test
    * [x] Windows releases work
        * [x] archives
        * [x] installer
    * [x] Mac releases work
        * [x] archive
        * [x] dmg
