### ISSUE TITLE
Improve the minimap

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#788]
__Tasks__

* [x] Ensure minimap always shows full diagram contents (https://github.com/bpmn-io/diagram-js-minimap/issues/4); essentially we should simply adapt to [this behavior](https://codepen.io/billdwhite/pen/QwpYZa)
* [x] Suppress diagram zoom on minimap focus (https://github.com/camunda/camunda-modeler/issues/639)
* [x] Suppress native pinch gesture on minimap pinch (https://github.com/camunda/camunda-modeler/issues/568)
* [x] Make expanding / collapsing of the minimap more obvious (https://github.com/camunda/camunda-modeler/issues/662)
