### ISSUE TITLE
Build Camunda Modeler @next (3.0.0-0)

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#866]
This issue collects items relevant for our upcoming Camunda Modeler (`next`) releases.

__Note:__ Moved future targets to https://github.com/camunda/camunda-modeler/issues/1116.

### Target: `3.0.0-0`

* [x] Release `camunda-modeler@3.0.0-0` (https://github.com/camunda/camunda-modeler/issues/1112)
* [x] DMN properties panel input blurred on commandStack.changed (https://github.com/camunda/camunda-modeler/issues/1100) @pinussilvestrus 
* [x] Add `GIVE FEEDBACK` button (https://github.com/camunda/camunda-modeler/issues/1094) @barmac 
* [x] Edit menu hides when switching to DMN editor (https://github.com/camunda/camunda-modeler/issues/1097) @barmac 
* [x] Set modeler version and name on diagram export (https://github.com/camunda/camunda-modeler/issues/1078) @barmac 
* [x] Export as image uses invalid extensions on MacOS (https://github.com/camunda/camunda-modeler/issues/1102)
* [x] Error when trying to export diagram as a jpg file (https://github.com/camunda/camunda-modeler/issues/1103) @philippfromme 
* [x] Integrate CommandStack#undo and CommandStack#redo when working with the properties panel (https://github.com/camunda/camunda-modeler/issues/1059, https://github.com/camunda/camunda-modeler/issues/1105) @philippfromme 
* [x] Select all in properties panel (https://github.com/camunda/camunda-modeler/issues/1095) @philippfromme 
* [x] Integrate window resized handling (https://github.com/camunda/camunda-modeler/issues/1082) @barmac 
* [x] Properties panel resizing is painfully slow (https://github.com/camunda/camunda-modeler/issues/1081) @barmac 
* [x] Update properties panel scrollers on properties panel resize (https://github.com/camunda/camunda-modeler/issues/1080) @barmac 
* [x] Implement correct dirty state indicators for all editors (https://github.com/camunda/camunda-modeler/issues/1023) @philippfromme
* [x] Copy log does not work anymore (https://github.com/camunda/camunda-modeler/issues/1079)
* [x] Integrate new client + `create-react-app` into dev setup
* [x] Implement basic life-cycle hooks
* [x] Try out styling without `styled-components` :+1: 
* [x] Drop create-react-app (#881)
* [x] Drop styled components
* [x] Integrate Open / Close tab actions (https://github.com/camunda/camunda-modeler/issues/885)
* [x] Integrate tab saving (https://github.com/camunda/camunda-modeler/issues/894)
* [x] Integrate tab links context menu
* [x] Integrate per-editor context menu
* [x] Integrate CMMN
* [x] Restore custom BPMN / DMN editors
* [x] Port all Toolbar actions
* [x] Make creating new DMN table possible (https://github.com/camunda/camunda-modeler/issues/909)
* [x] Wire edit menu and editor shortcuts (https://github.com/camunda/camunda-modeler/issues/907)
* [x] Make image export toolbar action work (https://github.com/camunda/camunda-modeler/issues/908)
* [x] Properly mount / unmount dmn-js-properties-panel (https://github.com/camunda/camunda-modeler/issues/902)
* [x] Restore robust error handling (https://github.com/camunda/camunda-modeler/issues/896)
* [x] Restore properties panel toggling / resizing / minimap toggling (https://github.com/camunda/camunda-modeler/issues/911)
* [x] Restore empty tab behavior (https://github.com/camunda/camunda-modeler/issues/919)
* [x] Restore workspace integration (#910)
* [x] Fix properties panel toggle jump (with multiple screens) (https://github.com/camunda/camunda-modeler/commit/4bcf8da458d30e092522d5b74edfa26a06f8752c)
* [x] Add log component (https://github.com/camunda/camunda-modeler/issues/931)
* [x] Expose errors and warnings in application log (https://github.com/camunda/camunda-modeler/issues/936)
* [x] Restore opening fallback sheet on import error behavior (https://github.com/camunda/camunda-modeler/issues/946)
* [x] Restore import error dialog behavior (https://github.com/camunda/camunda-modeler/issues/937)
* [x] Restore tab scrolling / dragging (https://github.com/camunda/camunda-modeler/issues/895)
* [x] Restore undo / redo behavior in XML tab (https://github.com/camunda/camunda-modeler/issues/956)
* [x] Restore file menu behavior (https://github.com/camunda/camunda-modeler/issues/963)
* [x] Restore diagram context menu (https://github.com/camunda/camunda-modeler/issues/1000)
* [x] Fix error switching form Diagram to XML tab (https://github.com/camunda/camunda-modeler/issues/934)
* [x] Refactor application menu (https://github.com/camunda/camunda-modeler/issues/967)
* [x] Refactor hardcoded dialogs (https://github.com/camunda/camunda-modeler/issues/959)
* [x] Restore file changed notifications (https://github.com/camunda/camunda-modeler/issues/970) 
* [x] Fix XML Editor layout (https://github.com/camunda/camunda-modeler/issues/1029)@pinussilvestrus 
* [x] Restore ability to create a diagram from an emtpy file (https://github.com/camunda/camunda-modeler/issues/1045)
* [x] Restore shortcuts fix (https://github.com/camunda/camunda-modeler/issues/1027) @philippfromme 
* [x] Restore ability to infer diagram type from file contents (https://github.com/camunda/camunda-modeler/issues/1044) @nikku
* [x] Fix MacOS-related build issue (https://github.com/camunda/camunda-modeler/issues/1048)
* [x] Restore edit menu behavior (https://github.com/camunda/camunda-modeler/issues/1024)
* [x] Make deploy toolbar action work (https://github.com/camunda/camunda-modeler/issues/906) @barmac 
* [x] Use filesystem when restoring workspace (https://github.com/camunda/camunda-modeler/issues/1002)
* [x] Fix edit menu activation (https://github.com/camunda/camunda-modeler/issues/1070)
* [x] Integrate element templates (https://github.com/camunda/camunda-modeler/issues/1001) @barmac 
* [x] Disable keyboard shortcuts if modal dialogs are open (https://github.com/camunda/camunda-modeler/issues/929) @barmac

**Comment by nikku** [comment]
Work happens on [`866-close-devil` feature branch](https://github.com/camunda/camunda-modeler/tree/866-close-devil).

**Comment by philippfromme** [comment]
What is meant by _Restore undo/redo behavior in XML tab_?

**Comment by philippfromme** [comment]
What is meant by _Restore undo/redo behavior in XML tab_?

**Comment by barmac** [comment]
Released 🎉 

https://github.com/camunda/camunda-modeler/issues/1112
