### ISSUE TITLE
Make deploy toolbar action work

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#906]
Button exists in toolbar but doesn't work, yet.

---

We plan to improve the current deploy functionality (2.x) in the following aspects:

* [x] Display endpoint to deploy to to user in deploy dialog
* [x] Improve deployment error handling (https://github.com/camunda/camunda-modeler/issues/838, https://github.com/camunda/camunda-modeler/issues/846)
* [x] Remember entered endpoint
* [x] Disable shortcuts when deployment modal is active (https://github.com/camunda/camunda-modeler/issues/929)
* [x] Support deployment against authenticated engines (https://github.com/camunda/camunda-modeler/issues/741)
* [x] Change deployment strategy to deploy only changed resources (https://github.com/camunda/camunda-modeler/issues/744)

Pulled support for more than one deployment endpoint (https://github.com/camunda/camunda-modeler/issues/804) out for now.

**Comment by barmac** [comment]
[ ] Use log for deployment errors
[ ] Get rid of `Sorry`
[ ] Allow to provide just the root URL (without `deployment/create`

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1063.
